#!/usr/bin/env bash
#A loop that repeat echo 10 times
i=1
while [ "$i" -le 10 ]
do
	case $i in
	4) echo -e "$i\nbad luck from China"
		((i++));;
	9) echo -e "$i\nbad luck from Japan"
		((i++));;
	17) echo -e "$i\nbad luck from Italy"
		((i++));;
	*) echo $i
		((i++));;
	esac
done	
