#!/usr/bin/env bash
#A loop that repeat echo 10 times
hour=0
minute=1
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	((hour++))
	minute=1
	while [ "$minute" -le 59 ]
	do
		echo $minute
		((minute++))
	done
done
