#!/usr/bin/env bash
#A loop that repeat echo 10 times
if [ -e school ]
then 
	if [ -s school ]
	then 
		echo school file is not empty
	else
		echo school file is empty
	fi
	if [ -f school ] 
	then
		echo school is a regular file
	fi
echo school file exists
else 
	echo school file does not exist
fi

