#!/usr/bin/env bash
#This script will display its own PID
exec(){ ./manage_my_process & /; }
kill(){ kill "$(cat /var/run/my_process.pid)"; }
delete(){ sudo rm /var/run/my_process.pid; }
create(){ echo "$!" > /var/run/my_process.pid; }
if [ "$1" == "start" ]; then
	exec; create
	echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
	kill; delete
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
	kill; delete; exec; create
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
